;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3-devkitc-02

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
extra_scripts = pre:platformio_extra.py
upload_speed = 115200
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
monitor_filters = 
    default
    time

; ============================================================================
; ============================================================================
build_flags = 
    -O2
    -ffast-math
    -funroll-loops

lib_deps =
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo @ ^1.1.0
    olikraus/U8g2 @ ^2.35.20

[env:native]
platform = native
build_flags = -std=c++17 -DNATIVE_TEST
test_framework = unity
